name: databricks_sql_project
description: ''
version: 0.0.1
author: null
language: sql
buildSystem: ''
buildSystemDetails: null
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/test1:
    name: test1
    description: ''
    fabricUID: 8
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-05-29 10:56:33'
    author: ashish@prophecy.io
  jobs/demo-job:
    name: demo-job
    description: ''
    fabricUID: 8
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-06-04 10:24:59'
    author: ashish@prophecy.io
  jobs/dmeo-job2:
    name: dmeo-job2
    description: ''
    fabricUID: 8
    scheduler:
      Composer: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-06-04 15:39:44'
    author: ashish@prophecy.io
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-05-29 06:26:35'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/customers_orders:
    name: customers_orders
    schema:
      providerType: Databricks
      fields:
      - name: total_orders
        dataType:
          type: Bigint
      - name: total_amount
        dataType:
          type: Bigint
      - name: customer_id
        dataType:
          type: String
      - name: full_name
        dataType:
          type: String
    description: null
    author: ashish@prophecy.io
    files:
    - models/customers_orders.sql
    - .prophecy/ide/models/customers_orders.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-30 08:28:08'
  .prophecy/metadata/sqlmodels/orders_summary:
    name: orders_summary
    schema:
      providerType: Databricks
      fields:
      - name: total_orders
        dataType:
          type: Bigint
      - name: total_amount
        dataType:
          type: Bigint
      - name: date
        dataType:
          type: String
      - name: unique_customers
        dataType:
          type: Bigint
    description: null
    author: ashish@prophecy.io
    files:
    - models/orders_summary.sql
    - .prophecy/ide/models/orders_summary.json
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2024-05-30 08:36:48'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources:
  .prophecy/metadata/sqlsources/hive_metastore_pooja:
    name: hive_metastore.pooja
    description: null
    author: ashish@prophecy.io
    files:
    - prophecy-sources/sources.yml
    createdAt: '2024-05-29 06:45:48'
    tables:
    - name: customers
      schema:
        providerType: databricks
        fields: []
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-29 06:45:48'
    - name: orders_new
      schema:
        providerType: databricks
        fields: []
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-29 06:46:19'
    - name: orders
      schema:
        providerType: databricks
        fields: []
      description: null
      author: ashish@prophecy.io
      createdAt: '2024-05-30 07:22:50'
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: ashish@prophecy.io
  createdAt: '2024-05-29 06:26:35'
dependencies: []
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
