---
version: 2
sources:
- name: "hive_metastore.pooja"
  database: "hive_metastore"
  schema: "pooja"
  config:
    enabled: true
  tables:
  - name: "customers"
    columns:
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "phone"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country_code"
      dataType:
        type: "String"
    - name: "account_open_date"
      dataType:
        type: "String"
    - name: "account_flags"
      dataType:
        type: "String"
  - name: "orders_new"
    columns:
    - name: "order_id"
      dataType:
        type: "String"
    - name: "customer_id"
      dataType:
        type: "String"
    - name: "order_status"
      dataType:
        type: "String"
    - name: "order_date"
      dataType:
        type: "String"
    - name: "amount"
      dataType:
        type: "Integer"
